name: Production Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push request event for the master branch
  push:    
    branches: [master]

jobs:
  deploy:
    # Our previously created self-hosted runner
    runs-on: self-hosted

    strategy:
      matrix:
        dotnet: ["8.0.x"]

    # A sequence of tasks that will execute as part of the job
    steps:
      # Checks out repository so our job can access it
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Stop the apps
        run: |
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          systemctl --user stop k9-koinz-camp.service
          systemctl --user stop k9-koinz-rian.service
          systemctl --user stop k9-koinz-skunk.service
          systemctl --user stop k9-koinz-test.service
          systemctl --user stop k9-koinz-ethan.service
          systemctl --user stop k9-koinz-beason.service

      # We will output publish files to the folder we previously created
      - name: Publish Camp
        run: dotnet publish -c Release -o /var/www/k9-koinz-camp

      - name: Publish Rian
        run: dotnet publish -c Release -o /var/www/k9-koinz-rian

      - name: Publish Snowie
        run: dotnet publish -c Release -o /var/www/k9-koinz-skunk

      - name: Publish Staging
        run: dotnet publish -c Release -o /var/www/k9-koinz-test

      - name: Publish Beason
        run: dotnet publish -c Release -o /var/www/k9-koinz-beason

      - name: Publish Ethan
        run: dotnet publish -c Release -o /var/www/k9-koinz-ethan

      - name: Restart the apps
        run: |
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          systemctl --user start k9-koinz-camp.service
          systemctl --user start k9-koinz-rian.service
          systemctl --user start k9-koinz-skunk.service
          systemctl --user start k9-koinz-test.service
          systemctl --user start k9-koinz-beason.service
          systemctl --user start k9-koinz-ethan.service
